GET http://localhost:3000/api/v1/loan/F422B567
Accept: application/json

###
GET http://localhost:3000/api/v1/loans/default?year=2018
Accept: application/json

###
GET http://localhost:3000/api/v1/loans/default-exchanged?year=2017
Accept: application/json

###
GET http://localhost:3000/api/v1/loans/distribution?startDate=01/01/2015&endDate=01/01/2018
Accept: application/json

###
GET http://localhost:3000/api/v1/loans/filter?filterType=education&value=tertiary
Accept: application/json
